# 3-Class Transformer Sentiment Pipeline

**High-level summary:**  
An end-to-end PyTorch Transformer pipeline that builds an enhanced tokenizer & vocabulary, defines a pre-layer-norm multi-head attention Transformer, trains with OneCycleLR & label smoothing on imbalanced data, evaluates with detailed metrics, and provides an inference utility for new text.

In [14]:
# prompt: connect google drive

from google.colab import drive
drive.mount('/content/drive')

# prompt: load current directory

import os

os.chdir('/content/drive/My Drive/CS605-NLP-Project')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [15]:
import pandas as pd
import numpy as np

class FinalScoreAnalyzer:
    def __init__(self, alpha=0.5):
        """
        Initialize analyzer with weight parameter
        alpha: weight for true_label (default 0.5 for equal weighting)
        """
        # Target categories to analyze
        self.target_categories = [
                "minute of minion mayhem",
                "despicable me family portrait",
                "gru lucy",
                "minion dance party",
                "mel s mixtape",
                "pantages hollywood theater trolls hug time jubilee",
                "lake hollywood spectacular",
                "po and master tigress",
                "lights camera action",
                "rhythm truck",
                "sesame street",
                "transformers voices of cybertron",
                "aset warrior",
                "anubis guards",
                "egyptian guards",
                "hatched featuring dr rodney",
                "waterworld",
                "baby kilos naptime tango",
                "raptor encounter with blue",
                "raptor encounter generations",
                "donkey live",
                "fortune favors the furry",
                "shrek 4 d adventure",
                "happily ever after"
        ]

        self.alpha = alpha

    def calculate_final_scores(self, input_file, output_file=None, alpha=None):
        """
        Calculate final scores using formula: final_score = a * true_label + (1-a) * ensemble_prediction
        """
        if alpha is not None:
            self.alpha = alpha

        try:
            # Read the input file
            if input_file.lower().endswith('.csv'):
                df = pd.read_csv(input_file)
            else:
                df = pd.read_excel(input_file)

            print(f"Loaded {len(df)} records from {input_file}")
            print(f"Using alpha = {self.alpha} (weight for true_label)")

            # Check required columns
            required_cols = ['Matched_Categories', 'true_label', 'ensemble_prediction']
            missing_cols = [col for col in required_cols if col not in df.columns]

            if missing_cols:
                print(f"Error: Missing required columns: {missing_cols}")
                print(f"Available columns: {list(df.columns)}")
                return None, None

            # Initialize results dataframe
            results_df = df.copy()

            # Add category-specific columns
            for category in self.target_categories:
                clean_name = category.replace(' ', '_').replace("'", "").replace('-', '_')
                results_df[f'category_match_{clean_name}'] = 0
                results_df[f'final_score_{clean_name}'] = 0.0

            # Process each row
            for idx, row in results_df.iterrows():
                matched_categories = str(row['Matched_Categories'])
                true_label = row['true_label']
                ensemble_prediction = row['ensemble_prediction']

                # Validate values are in expected range (0, 1, 2)
                if true_label not in [0, 1, 2] or ensemble_prediction not in [0, 1, 2]:
                    print(f"Warning: Row {idx} has unexpected values - true_label: {true_label}, ensemble_prediction: {ensemble_prediction}")

                if matched_categories and matched_categories != '' and matched_categories != 'nan':
                    # Split multiple categories
                    categories = [cat.strip() for cat in matched_categories.split('|')]

                    # Check each target category
                    for target_category in self.target_categories:
                        clean_name = target_category.replace(' ', '_').replace("'", "").replace('-', '_')

                        # Check if this target category appears in matched categories
                        if target_category in categories:
                            results_df.at[idx, f'category_match_{clean_name}'] = 1

                            # Calculate final score using the formula
                            final_score = self.alpha * true_label + (1 - self.alpha) * ensemble_prediction
                            results_df.at[idx, f'final_score_{clean_name}'] = final_score

            # Save individual results if output file specified
            if output_file:
                if output_file.lower().endswith('.csv'):
                    results_df.to_csv(output_file, index=False)
                else:
                    results_df.to_excel(output_file, index=False)
                print(f"Individual results saved to {output_file}")

            # Create grouped analysis
            grouped_results = self.create_grouped_analysis(results_df, min_count=30)

            return results_df, grouped_results

        except Exception as e:
            print(f"Error: {str(e)}")
            return None, None

    def create_grouped_analysis(self, df, min_count=30):
        """
        Group by categories and calculate mean final scores, ranked by mean final score
        Only show categories with count >= min_count
        """
        print("\n" + "="*80)
        print("FINAL SCORE ANALYSIS - GROUPED BY CATEGORIES")
        print("="*80)

        grouped_data = []

        for category in self.target_categories:
            clean_name = category.replace(' ', '_').replace("'", "").replace('-', '_')

            category_match_col = f'category_match_{clean_name}'
            final_score_col = f'final_score_{clean_name}'

            if category_match_col in df.columns and final_score_col in df.columns:
                # Only calculate for rows where this category was matched
                category_rows = df[df[category_match_col] == 1]

                if len(category_rows) > 0:
                    total_occurrences = len(category_rows)
                    mean_final_score = category_rows[final_score_col].mean()
                    min_final_score = category_rows[final_score_col].min()
                    max_final_score = category_rows[final_score_col].max()
                    std_final_score = category_rows[final_score_col].std()

                    grouped_data.append({
                        'category': category,
                        'total_occurrences': int(total_occurrences),
                        'mean_final_score': mean_final_score,
                        'min_final_score': min_final_score,
                        'max_final_score': max_final_score,
                        'std_final_score': std_final_score if not pd.isna(std_final_score) else 0.0
                    })

        # Create grouped DataFrame
        grouped_df = pd.DataFrame(grouped_data)

        # Filter by minimum count
        filtered_df = grouped_df[grouped_df['total_occurrences'] >= min_count].copy()

        # Sort by mean final score (descending) - this is the ranking you requested
        filtered_df = filtered_df.sort_values('mean_final_score', ascending=False)
        filtered_df = filtered_df.reset_index(drop=True)
        filtered_df['rank'] = filtered_df.index + 1

        # Display results
        print(f"\nFINAL SCORE RANKINGS (Alpha = {self.alpha}, Min Count = {min_count}):")
        print("-" * 100)

        if len(filtered_df) > 0:
            print(f"{'Rank':<5} {'Category':<45} {'Count':<8} {'Mean Score':<12} {'Min':<8} {'Max':<8} {'Std':<8}")
            print("-" * 100)

            for _, row in filtered_df.iterrows():
                print(f"{row['rank']:<5} {row['category']:<45} {row['total_occurrences']:<8} "
                      f"{row['mean_final_score']:<12.4f} {row['min_final_score']:<8.2f} "
                      f"{row['max_final_score']:<8.2f} {row['std_final_score']:<8.4f}")
        else:
            print(f"No categories found with count >= {min_count}")

        # Additional insights
        print(f"\n" + "="*80)
        print("ANALYSIS SUMMARY:")
        print("="*80)

        total_records = len(df)
        categories_found = len(grouped_df)
        categories_displayed = len(filtered_df)

        print(f"📊 Total records analyzed: {total_records}")
        print(f"🎯 Categories found: {categories_found}/{len(self.target_categories)}")
        print(f"📈 Categories displayed (count >= {min_count}): {categories_displayed}/{categories_found}")
        print(f"⚖️  Alpha (true_label weight): {self.alpha}")
        print(f"⚖️  Beta (ensemble_prediction weight): {1-self.alpha}")

        if len(filtered_df) > 0:
            print(f"🏆 Top ranked category: {filtered_df.iloc[0]['category']} (score: {filtered_df.iloc[0]['mean_final_score']:.4f})")
            if len(filtered_df) > 1:
                print(f"🥈 Second ranked: {filtered_df.iloc[1]['category']} (score: {filtered_df.iloc[1]['mean_final_score']:.4f})")
            if len(filtered_df) > 2:
                print(f"🥉 Third ranked: {filtered_df.iloc[2]['category']} (score: {filtered_df.iloc[2]['mean_final_score']:.4f})")

        # Show categories that were filtered out (below min_count)
        below_threshold = grouped_df[grouped_df['total_occurrences'] < min_count]
        if len(below_threshold) > 0:
            print(f"\n📋 Categories below threshold (count < {min_count}):")
            for _, row in below_threshold.sort_values('total_occurrences', ascending=False).iterrows():
                print(f"   - {row['category']}: {row['total_occurrences']} occurrences")

        # Categories not found at all
        found_categories = set(grouped_df['category'].tolist())
        not_found = [cat for cat in self.target_categories if cat not in found_categories]
        if not_found:
            print(f"\n🔍 Categories not found ({len(not_found)}):")
            for cat in not_found:
                print(f"   - {cat}")

        print("="*80)

        return filtered_df

    def save_grouped_results(self, grouped_df, filename):
        """Save grouped results to file"""
        if filename.lower().endswith('.csv'):
            grouped_df.to_csv(filename, index=False)
        else:
            grouped_df.to_excel(filename, index=False)
        print(f"Grouped results saved to {filename}")

    def analyze_with_different_alphas(self, input_file, alphas=[0.3, 0.5, 0.7]):
        """
        Compare results with different alpha values
        """
        print("COMPARING DIFFERENT ALPHA VALUES:")
        print("="*50)

        all_results = {}

        for alpha in alphas:
            print(f"\nAnalyzing with alpha = {alpha}")
            print("-" * 30)

            _, grouped_df = self.calculate_final_scores(input_file, alpha=alpha)
            if grouped_df is not None and len(grouped_df) > 0:
                all_results[alpha] = grouped_df[['category', 'mean_final_score']].copy()
                all_results[alpha].columns = ['category', f'score_alpha_{alpha}']

                # Show top 5
                print(f"Top 5 categories (alpha={alpha}):")
                for i, row in grouped_df.head(5).iterrows():
                    print(f"  {i+1}. {row['category']}: {row['mean_final_score']:.4f}")

        return all_results

    def analyze_from_file(self, input_file, individual_output=None, grouped_output=None, alpha=0.5, min_count=30):
        """
        Complete analysis workflow
        """
        print("Starting Final Score Analysis...")
        print(f"Formula: final_score = {alpha} * true_label + {1-alpha} * ensemble_prediction")
        print(f"Target categories: {len(self.target_categories)}")
        print(f"Minimum count threshold: {min_count}")

        # Perform analysis
        individual_df, grouped_df = self.calculate_final_scores(input_file, individual_output, alpha)

        if grouped_df is not None and grouped_output:
            self.save_grouped_results(grouped_df, grouped_output)

        return individual_df, grouped_df


# Example usage and testing
if __name__ == "__main__":
    # Initialize analyzer
    analyzer = FinalScoreAnalyzer(alpha=0.5)

    print("Final Score Analyzer")
    print("="*50)
    print(f"Formula: final_score = a * true_label + (1-a) * ensemble_prediction")
    print(f"Expected values: true_label, ensemble_prediction ∈ {0, 1, 2}")
    print(f"Target categories: {len(analyzer.target_categories)}")

    print("\n" + "="*50)
    print("USAGE EXAMPLES:")
    print("="*50)

    print("\n1. Basic analysis with default alpha=0.5:")
    print("analyzer.analyze_from_file('your_data.csv')")

    print("\n2. Analysis with custom parameters:")
    print("analyzer.analyze_from_file(")
    print("    'your_data.csv',")
    print("    individual_output='detailed_scores.csv',")
    print("    grouped_output='category_rankings.csv',")
    print("    alpha=0.7,      # Give more weight to true_label")
    print("    min_count=50    # Only show categories with 50+ occurrences")
    print(")")

    print("\n3. Compare different alpha values:")
    print("results = analyzer.analyze_with_different_alphas(")
    print("    'your_data.csv',")
    print("    alphas=[0.3, 0.5, 0.7]")
    print(")")

    print("\nExpected input columns:")
    print("- Matched_Categories: categories found (separated by |)")
    print("- true_label: ground truth value (0, 1, or 2)")
    print("- ensemble_prediction: model prediction (0, 1, or 2)")

    print("\nOutput: Categories ranked by mean final score!")

Final Score Analyzer
==================================================
Formula: final_score = a * true_label + (1-a) * ensemble_prediction
Expected values: true_label, ensemble_prediction ∈ (0, 1, 2)
Target categories: 24

==================================================
USAGE EXAMPLES:
==================================================

1. Basic analysis with default alpha=0.5:
analyzer.analyze_from_file('your_data.csv')

2. Analysis with custom parameters:
analyzer.analyze_from_file(
    'your_data.csv',
    individual_output='detailed_scores.csv',
    grouped_output='category_rankings.csv',
    alpha=0.7,      # Give more weight to true_label
    min_count=50    # Only show categories with 50+ occurrences
)

3. Compare different alpha values:
results = analyzer.analyze_with_different_alphas(
    'your_data.csv',
    alphas=[0.3, 0.5, 0.7]
)

Expected input columns:
- Matched_Categories: categories found (separated by |)
- true_label: ground truth value (0, 1, or 2)
- ensemble_prediction: model prediction (0, 1, or 2)

Output: Categories ranked by mean final score!

In [16]:

# Initialize with default alpha=0.5 (equal weighting)
analyzer = FinalScoreAnalyzer(alpha=0.5)

analyzer.analyze_from_file(
    'datastore/google_reviews_adaptive_moe_results_classified.csv',
    individual_output='result/shows_detailed_scores.csv',
    grouped_output='result/shows_category_rankings.csv',
    alpha=0.5,      # Weight for true_label
    min_count=50    # Only show categories with 50+ occurrences
)

# Test different weightings
results = analyzer.analyze_with_different_alphas(
    'datastore/google_reviews_adaptive_moe_results_classified.csv',
    alphas=[0.1,0.3 , 0.5, 0.7, 0.9]
)

Starting Final Score Analysis...
Formula: final_score = 0.5 * true_label + 0.5 * ensemble_prediction
Target categories: 24
Minimum count threshold: 50
Loaded 29412 records from datastore/google_reviews_adaptive_moe_results_classified.csv
Using alpha = 0.5 (weight for true_label)
Individual results saved to result/shows_detailed_scores.csv

================================================================================
FINAL SCORE ANALYSIS - GROUPED BY CATEGORIES
================================================================================

FINAL SCORE RANKINGS (Alpha = 0.5, Min Count = 30):
----------------------------------------------------------------------------------------------------
Rank  Category                                      Count    Mean Score   Min      Max      Std
----------------------------------------------------------------------------------------------------
1     lights camera action                          99       1.7273       0.00     2.00     0.5545
2     transformers voices of cybertron              2179     1.7095       0.00     2.00     0.5310
3     shrek 4 d adventure                           424      1.7064       0.00     2.00     0.5173
4     waterworld                                    928      1.6552       0.00     2.00     0.5945
5     lake hollywood spectacular                    63       1.5397       0.50     2.00     0.2739
6     pantages hollywood theater trolls hug time jubilee 52       1.4904       0.50     2.00     0.2710
7     minute of minion mayhem                       464      1.4795       0.00     2.00     0.6768
8     minion dance party                            450      1.4744       0.00     2.00     0.6756
9     sesame street                                 47       1.4681       0.00     2.00     0.6789

================================================================================
ANALYSIS SUMMARY:
================================================================================
📊 Total records analyzed: 29412
🎯 Categories found: 21/24
📈 Categories displayed (count >= 30): 9/21
⚖️  Alpha (true_label weight): 0.5
⚖️  Beta (ensemble_prediction weight): 0.5
🏆 Top ranked category: lights camera action (score: 1.7273)
🥈 Second ranked: transformers voices of cybertron (score: 1.7095)
🥉 Third ranked: shrek 4 d adventure (score: 1.7064)

📋 Categories below threshold (count < 30):
   - egyptian guards: 24 occurrences
   - donkey live: 21 occurrences
   - gru lucy: 20 occurrences
   - happily ever after: 8 occurrences
   - rhythm truck: 5 occurrences
   - despicable me family portrait: 4 occurrences
   - po and master tigress: 4 occurrences
   - baby kilos naptime tango: 4 occurrences
   - raptor encounter generations: 4 occurrences
   - raptor encounter with blue: 3 occurrences
   - fortune favors the furry: 2 occurrences
   - hatched featuring dr rodney: 1 occurrences

🔍 Categories not found (3):
   - mel s mixtape
   - aset warrior
   - anubis guards
================================================================================
Grouped results saved to result/shows_category_rankings.csv
COMPARING DIFFERENT ALPHA VALUES:
==================================================

Analyzing with alpha = 0.1
------------------------------
Loaded 29412 records from datastore/google_reviews_adaptive_moe_results_classified.csv
Using alpha = 0.1 (weight for true_label)

================================================================================
FINAL SCORE ANALYSIS - GROUPED BY CATEGORIES
================================================================================

FINAL SCORE RANKINGS (Alpha = 0.1, Min Count = 30):
----------------------------------------------------------------------------------------------------
Rank  Category                                      Count    Mean Score   Min      Max      Std
----------------------------------------------------------------------------------------------------
1     lights camera action                          99       1.6545       0.00     2.00     0.6683
2     transformers voices of cybertron              2179     1.6166       0.00     2.00     0.6534
3     shrek 4 d adventure                           424      1.6092       0.00     2.00     0.6402
4     waterworld                                    928      1.5707       0.00     2.00     0.6960
5     minute of minion mayhem                       464      1.3597       0.00     2.00     0.7664
6     minion dance party                            450      1.3527       0.00     2.00     0.7667
7     sesame street                                 47       1.3489       0.00     2.00     0.7532
8     lake hollywood spectacular                    63       1.2349       0.90     2.00     0.3370
9     pantages hollywood theater trolls hug time jubilee 52       1.1596       0.20     2.00     0.3057

================================================================================
ANALYSIS SUMMARY:
================================================================================
📊 Total records analyzed: 29412
🎯 Categories found: 21/24
📈 Categories displayed (count >= 30): 9/21
⚖️  Alpha (true_label weight): 0.1
⚖️  Beta (ensemble_prediction weight): 0.9
🏆 Top ranked category: lights camera action (score: 1.6545)
🥈 Second ranked: transformers voices of cybertron (score: 1.6166)
🥉 Third ranked: shrek 4 d adventure (score: 1.6092)

📋 Categories below threshold (count < 30):
   - egyptian guards: 24 occurrences
   - donkey live: 21 occurrences
   - gru lucy: 20 occurrences
   - happily ever after: 8 occurrences
   - rhythm truck: 5 occurrences
   - despicable me family portrait: 4 occurrences
   - po and master tigress: 4 occurrences
   - baby kilos naptime tango: 4 occurrences
   - raptor encounter generations: 4 occurrences
   - raptor encounter with blue: 3 occurrences
   - fortune favors the furry: 2 occurrences
   - hatched featuring dr rodney: 1 occurrences

🔍 Categories not found (3):
   - mel s mixtape
   - aset warrior
   - anubis guards
================================================================================
Top 5 categories (alpha=0.1):
  1. lights camera action: 1.6545
  2. transformers voices of cybertron: 1.6166
  3. shrek 4 d adventure: 1.6092
  4. waterworld: 1.5707
  5. minute of minion mayhem: 1.3597

Analyzing with alpha = 0.3
------------------------------
Loaded 29412 records from datastore/google_reviews_adaptive_moe_results_classified.csv
Using alpha = 0.3 (weight for true_label)

================================================================================
FINAL SCORE ANALYSIS - GROUPED BY CATEGORIES
================================================================================

FINAL SCORE RANKINGS (Alpha = 0.3, Min Count = 30):
----------------------------------------------------------------------------------------------------
Rank  Category                                      Count    Mean Score   Min      Max      Std
----------------------------------------------------------------------------------------------------
1     lights camera action                          99       1.6909       0.00     2.00     0.6024
2     transformers voices of cybertron              2179     1.6631       0.00     2.00     0.5832
3     shrek 4 d adventure                           424      1.6578       0.00     2.00     0.5714
4     waterworld                                    928      1.6129       0.00     2.00     0.6376
5     minute of minion mayhem                       464      1.4196       0.00     2.00     0.7113
6     minion dance party                            450      1.4136       0.00     2.00     0.7107
7     sesame street                                 47       1.4085       0.00     2.00     0.7061
8     lake hollywood spectacular                    63       1.3873       0.70     2.00     0.2904
9     pantages hollywood theater trolls hug time jubilee 52       1.3250       0.60     2.00     0.2700

================================================================================
ANALYSIS SUMMARY:
================================================================================
📊 Total records analyzed: 29412
🎯 Categories found: 21/24
📈 Categories displayed (count >= 30): 9/21
⚖️  Alpha (true_label weight): 0.3
⚖️  Beta (ensemble_prediction weight): 0.7
🏆 Top ranked category: lights camera action (score: 1.6909)
🥈 Second ranked: transformers voices of cybertron (score: 1.6631)
🥉 Third ranked: shrek 4 d adventure (score: 1.6578)

📋 Categories below threshold (count < 30):
   - egyptian guards: 24 occurrences
   - donkey live: 21 occurrences
   - gru lucy: 20 occurrences
   - happily ever after: 8 occurrences
   - rhythm truck: 5 occurrences
   - despicable me family portrait: 4 occurrences
   - po and master tigress: 4 occurrences
   - baby kilos naptime tango: 4 occurrences
   - raptor encounter generations: 4 occurrences
   - raptor encounter with blue: 3 occurrences
   - fortune favors the furry: 2 occurrences
   - hatched featuring dr rodney: 1 occurrences

🔍 Categories not found (3):
   - mel s mixtape
   - aset warrior
   - anubis guards
================================================================================
Top 5 categories (alpha=0.3):
  1. lights camera action: 1.6909
  2. transformers voices of cybertron: 1.6631
  3. shrek 4 d adventure: 1.6578
  4. waterworld: 1.6129
  5. minute of minion mayhem: 1.4196

Analyzing with alpha = 0.5
------------------------------
Loaded 29412 records from datastore/google_reviews_adaptive_moe_results_classified.csv
Using alpha = 0.5 (weight for true_label)

================================================================================
FINAL SCORE ANALYSIS - GROUPED BY CATEGORIES
================================================================================

FINAL SCORE RANKINGS (Alpha = 0.5, Min Count = 30):
----------------------------------------------------------------------------------------------------
Rank  Category                                      Count    Mean Score   Min      Max      Std
----------------------------------------------------------------------------------------------------
1     lights camera action                          99       1.7273       0.00     2.00     0.5545
2     transformers voices of cybertron              2179     1.7095       0.00     2.00     0.5310
3     shrek 4 d adventure                           424      1.7064       0.00     2.00     0.5173
4     waterworld                                    928      1.6552       0.00     2.00     0.5945
5     lake hollywood spectacular                    63       1.5397       0.50     2.00     0.2739
6     pantages hollywood theater trolls hug time jubilee 52       1.4904       0.50     2.00     0.2710
7     minute of minion mayhem                       464      1.4795       0.00     2.00     0.6768
8     minion dance party                            450      1.4744       0.00     2.00     0.6756
9     sesame street                                 47       1.4681       0.00     2.00     0.6789

================================================================================
ANALYSIS SUMMARY:
================================================================================
📊 Total records analyzed: 29412
🎯 Categories found: 21/24
📈 Categories displayed (count >= 30): 9/21
⚖️  Alpha (true_label weight): 0.5
⚖️  Beta (ensemble_prediction weight): 0.5
🏆 Top ranked category: lights camera action (score: 1.7273)
🥈 Second ranked: transformers voices of cybertron (score: 1.7095)
🥉 Third ranked: shrek 4 d adventure (score: 1.7064)

📋 Categories below threshold (count < 30):
   - egyptian guards: 24 occurrences
   - donkey live: 21 occurrences
   - gru lucy: 20 occurrences
   - happily ever after: 8 occurrences
   - rhythm truck: 5 occurrences
   - despicable me family portrait: 4 occurrences
   - po and master tigress: 4 occurrences
   - baby kilos naptime tango: 4 occurrences
   - raptor encounter generations: 4 occurrences
   - raptor encounter with blue: 3 occurrences
   - fortune favors the furry: 2 occurrences
   - hatched featuring dr rodney: 1 occurrences

🔍 Categories not found (3):
   - mel s mixtape
   - aset warrior
   - anubis guards
================================================================================
Top 5 categories (alpha=0.5):
  1. lights camera action: 1.7273
  2. transformers voices of cybertron: 1.7095
  3. shrek 4 d adventure: 1.7064
  4. waterworld: 1.6552
  5. lake hollywood spectacular: 1.5397

Analyzing with alpha = 0.7
------------------------------
Loaded 29412 records from datastore/google_reviews_adaptive_moe_results_classified.csv
Using alpha = 0.7 (weight for true_label)

================================================================================
FINAL SCORE ANALYSIS - GROUPED BY CATEGORIES
================================================================================

FINAL SCORE RANKINGS (Alpha = 0.7, Min Count = 30):
----------------------------------------------------------------------------------------------------
Rank  Category                                      Count    Mean Score   Min      Max      Std
----------------------------------------------------------------------------------------------------
1     lights camera action                          99       1.7636       0.00     2.00     0.5296
2     transformers voices of cybertron              2179     1.7559       0.00     2.00     0.5024
3     shrek 4 d adventure                           424      1.7550       0.00     2.00     0.4830
4     waterworld                                    928      1.6974       0.00     2.00     0.5702
5     lake hollywood spectacular                    63       1.6921       0.30     2.00     0.2925
6     pantages hollywood theater trolls hug time jubilee 52       1.6558       0.30     2.00     0.3083
7     minute of minion mayhem                       464      1.5394       0.00     2.00     0.6659
8     minion dance party                            450      1.5353       0.00     2.00     0.6647
9     sesame street                                 47       1.5277       0.00     2.00     0.6740

================================================================================
ANALYSIS SUMMARY:
================================================================================
📊 Total records analyzed: 29412
🎯 Categories found: 21/24
📈 Categories displayed (count >= 30): 9/21
⚖️  Alpha (true_label weight): 0.7
⚖️  Beta (ensemble_prediction weight): 0.30000000000000004
🏆 Top ranked category: lights camera action (score: 1.7636)
🥈 Second ranked: transformers voices of cybertron (score: 1.7559)
🥉 Third ranked: shrek 4 d adventure (score: 1.7550)

📋 Categories below threshold (count < 30):
   - egyptian guards: 24 occurrences
   - donkey live: 21 occurrences
   - gru lucy: 20 occurrences
   - happily ever after: 8 occurrences
   - rhythm truck: 5 occurrences
   - despicable me family portrait: 4 occurrences
   - po and master tigress: 4 occurrences
   - baby kilos naptime tango: 4 occurrences
   - raptor encounter generations: 4 occurrences
   - raptor encounter with blue: 3 occurrences
   - fortune favors the furry: 2 occurrences
   - hatched featuring dr rodney: 1 occurrences

🔍 Categories not found (3):
   - mel s mixtape
   - aset warrior
   - anubis guards
================================================================================
Top 5 categories (alpha=0.7):
  1. lights camera action: 1.7636
  2. transformers voices of cybertron: 1.7559
  3. shrek 4 d adventure: 1.7550
  4. waterworld: 1.6974
  5. lake hollywood spectacular: 1.6921

Analyzing with alpha = 0.9
------------------------------
Loaded 29412 records from datastore/google_reviews_adaptive_moe_results_classified.csv
Using alpha = 0.9 (weight for true_label)

================================================================================
FINAL SCORE ANALYSIS - GROUPED BY CATEGORIES
================================================================================

FINAL SCORE RANKINGS (Alpha = 0.9, Min Count = 30):
----------------------------------------------------------------------------------------------------
Rank  Category                                      Count    Mean Score   Min      Max      Std
----------------------------------------------------------------------------------------------------
1     lake hollywood spectacular                    63       1.8444       0.10     2.00     0.3407
2     pantages hollywood theater trolls hug time jubilee 52       1.8212       0.10     2.00     0.3712
3     shrek 4 d adventure                           424      1.8035       0.00     2.00     0.4729
4     transformers voices of cybertron              2179     1.8024       0.00     2.00     0.5014
5     lights camera action                          99       1.8000       0.00     2.00     0.5309
6     waterworld                                    928      1.7397       0.00     2.00     0.5670
7     minute of minion mayhem                       464      1.5994       0.00     2.00     0.6800
8     minion dance party                            450      1.5962       0.00     2.00     0.6793
9     sesame street                                 47       1.5872       0.00     2.00     0.6918

================================================================================
ANALYSIS SUMMARY:
================================================================================
📊 Total records analyzed: 29412
🎯 Categories found: 21/24
📈 Categories displayed (count >= 30): 9/21
⚖️  Alpha (true_label weight): 0.9
⚖️  Beta (ensemble_prediction weight): 0.09999999999999998
🏆 Top ranked category: lake hollywood spectacular (score: 1.8444)
🥈 Second ranked: pantages hollywood theater trolls hug time jubilee (score: 1.8212)
🥉 Third ranked: shrek 4 d adventure (score: 1.8035)

📋 Categories below threshold (count < 30):
   - egyptian guards: 24 occurrences
   - donkey live: 21 occurrences
   - gru lucy: 20 occurrences
   - happily ever after: 8 occurrences
   - rhythm truck: 5 occurrences
   - despicable me family portrait: 4 occurrences
   - po and master tigress: 4 occurrences
   - baby kilos naptime tango: 4 occurrences
   - raptor encounter generations: 4 occurrences
   - raptor encounter with blue: 3 occurrences
   - fortune favors the furry: 2 occurrences
   - hatched featuring dr rodney: 1 occurrences

🔍 Categories not found (3):
   - mel s mixtape
   - aset warrior
   - anubis guards
================================================================================
Top 5 categories (alpha=0.9):
  1. lake hollywood spectacular: 1.8444
  2. pantages hollywood theater trolls hug time jubilee: 1.8212
  3. shrek 4 d adventure: 1.8035
  4. transformers voices of cybertron: 1.8024
  5. lights camera action: 1.8000